version: '3.4'

services:
  cortex.in.api:
    image: neurul/cortex.in.api:0.2.14
    build:
      context: .
      dockerfile: ./main/Port.Adapter/In/Api/Dockerfile
  cortex.out.api:
    image: neurul/cortex.out.api:0.2.13
    build:
      context: .
      dockerfile: ./main/Port.Adapter/Out/Api/Dockerfile